# Generated by Django 3.2.3 on 2021-05-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('focus', '0002_quote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
